# This config file can become outdated! You may want to check the latest one if you have some issues.
# It can be found here: https://github.com/Kaluub/CKPrison/blob/master/src/config.yml

# Define the mines list here.
mines: # Example mines below.
#  mine_a:
#    rank: rank_a # The rank with relevance to this mine.
#    world: world # The name of the world to use (usually just 'world'.)
#    start: [20, -20, 20] # The coordinates of the first corner.
#    end: [0, 0, 0] # The coordinates of the second corner.
#    blocks: # List of block names to put in the mine.
#      - stone
#      - coal_ore
#      - diamond_ore
#    weights: # Weight of each block appearing (follows the order of blocks list.)
#      - 0.6
#      - 0.3
#      - 0.1
#  mine_b:
#    rank: rank_b
#    world: world
#    start: [60, 60, 60]
#    end: [80, 0, 80]
#    blocks:
#      - diamond_block
#      - emerald_block
#      - deepslate_emerald_ore
#    weights: # Weights do not need to add up to 1 or 100, you can use anything you prefer.
#      - 0.8
#      - 0.2
#      - 0.5

# Define the ranks here.
ranks: # Example ranks below.
#  rank_a:
#    rankup_price: 10 # Price to rank-up to the next rank.
#    next_rank: rank_b # The next rank's name, or just use 'next'. Prevents rank up if not present.
#    tag: '&7[&bA&7]&r' # Chat prefix (in your chat handler, set {prison_rank}.) Not required if you don't want it.
#  rank_b:
#    tag: '&7[&bB&7]&r'
#    # Inherits (in the context of which mines it can use) permissions from this rank.
#    # If not set, the rank inherits no ranks.
#    # You can use 'previous' and 'next' to use the previous and next rank
#    # Inheritance is chained, meaning if a rank_c inherits rank_b, it would then inherit rank_a as well.
#    inherits: previous
#    # A list of commands you'd like to be run upon ranking up to this level.
#    # To use the players name, you can use '%p' -- useful for giving them some item, for example.
#    # If you aren't using the name as part of the command, for example in a server broadcast, you can instead
#    # use their display name with '%d'.
#    # You can use '%r' for the ranks internal name.
#    rankup_commands:
#      - 'give %p minecraft:golden_apple'
#      - 'say Wow! Player %d earned rank B!'

# The default rank name. If not set, ranks will default to "none".
# Everybody will receive this when they first join.
default_rank: rank_a

# Mine reset interval (in seconds). Every mine will reset around the same time. Default: 10 minutes.
reset_interval: 600

# Defines the maximum size of each side length.
# For example, a mine which is 51x51x51 and a mine that is 1x1x100 would not be allowed if kept at 50.
# Increasing this could lead to making hard to fix mistakes without thorough backups.
# Larger mines also take longer to reset.
# It's recommended to use at most a 50x50x50 mine size to avoid these issues, if not smaller.
maximum_mine_size: 50

# Provide native block breaking/placing protection.
# This prevents blocks from being placed or broken outside of mines, and
# automatically allows players to break blocks inside of mines they unlocked.
# This is not a full protection! Use WorldGuard or anything of the like for extended protections.
# Players with OP or with the permission ckprison.admin are immune.
automatic_protection: true

# If automatic_protection is true, use the users rank to determine if they can break blocks in the mine.
# The mine must have a rank name supplied in order for this protection to apply!
rank_based_protection: false

# This allows you to set the maximum amount of blocks placed per tick when resetting the mines.
# Set to -1 to try placing all blocks on the same tick. This will cause lag spikes when resetting the mines!
blocks_placed_per_tick: 1000

# If set, you can choose a command for the player to run when they right click with their pickaxe.
# pickaxe_command: sell all